
set MATLAB=C:\Program Files\MATLAB\R2025a

gmake -f imperix_control.mk  GENERATE_ERT_S_FUNCTION=0 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MAT_FILE=0 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 GENERATE_ASAP2=0 EXT_MODE=0 EXTMODE_STATIC_ALLOC=1 EXTMODE_STATIC_ALLOC_SIZE=100000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 MODELREF_TARGET_TYPE=NONE RELATIVE_PATH_TO_ANCHOR=.. OPTS="-DTID01EQ=0"
